const uiTexts = {
  de: {
    autoTranslateLabel: "Automatische Übersetzung",
    copyBtnTitle: "Kopieren",
    interfaceLabel: "Benutzeroberfläche:",
    pasteBtnTitle: "Einfügen",
    serviceLabel: "Dienst:",
    sourceLangLabel: "Ausgangssprache",
    sourcePlaceholder: "Text eingeben...",
    targetLang1Label: "Zielsprache 1",
    targetLang2Label: "Zielsprache 2",
    translateButtonText: "Übersetzen",
    translation1Placeholder: "Übersetzung 1",
    translation2Placeholder: "Übersetzung 2",
  },
  en: {
    autoTranslateLabel: "Auto-translate",
    copyBtnTitle: "Copy",
    interfaceLabel: "Interface:",
    pasteBtnTitle: "Paste",
    serviceLabel: "Service:",
    sourceLangLabel: "Source Language",
    sourcePlaceholder: "Enter text...",
    targetLang1Label: "Target Language 1",
    targetLang2Label: "Target Language 2",
    translateButtonText: "Translate",
    translation1Placeholder: "Translation 1",
    translation2Placeholder: "Translation 2",
  },
  fr: {
    autoTranslateLabel: "Traduction automatique",
    copyBtnTitle: "Copier",
    interfaceLabel: "Interface:",
    pasteBtnTitle: "Coller",
    serviceLabel: "Service:",
    sourceLangLabel: "Langue source",
    sourcePlaceholder: "Saisir le texte...",
    targetLang1Label: "Langue cible 1",
    targetLang2Label: "Langue cible 2",
    translateButtonText: "Traduire",
    translation1Placeholder: "Traduction 1",
    translation2Placeholder: "Traduction 2",
  },
  nl: {
    autoTranslateLabel: "Automatisch vertalen",
    copyBtnTitle: "Kopiëren",
    interfaceLabel: "Interface:",
    pasteBtnTitle: "Plakken",
    serviceLabel: "Service:",
    sourceLangLabel: "Brontaal",
    sourcePlaceholder: "Tekst invoeren...",
    targetLang1Label: "Doeltaal 1",
    targetLang2Label: "Doeltaal 2",
    translateButtonText: "Vertaal",
    translation1Placeholder: "Vertaling 1",
    translation2Placeholder: "Vertaling 2",
  },
  pl: {
    autoTranslateLabel: "Automatyczne tłumaczenie",
    copyBtnTitle: "Kopiuj",
    interfaceLabel: "Interfejs:",
    pasteBtnTitle: "Wklej",
    serviceLabel: "Serwis:",
    sourceLangLabel: "Język źródłowy",
    sourcePlaceholder: "Wpisz tekst...",
    targetLang1Label: "Język docelowy 1",
    targetLang2Label: "Język docelowy 2",
    translateButtonText: "Tłumacz",
    translation1Placeholder: "Tłumaczenie 1",
    translation2Placeholder: "Tłumaczenie 2",
  },
  pt: {
    autoTranslateLabel: "Tradução automática",
    copyBtnTitle: "Copiar",
    interfaceLabel: "Interface:",
    pasteBtnTitle: "Colar",
    serviceLabel: "Serviço:",
    sourceLangLabel: "Idioma de origem",
    sourcePlaceholder: "Digite o texto...",
    targetLang1Label: "Idioma de destino 1",
    targetLang2Label: "Idioma de destino 2",
    translateButtonText: "Traduzir",
    translation1Placeholder: "Tradução 1",
    translation2Placeholder: "Tradução 2",
  },
  ru: {
    autoTranslateLabel: "Автоперевод",
    copyBtnTitle: "Копировать",
    interfaceLabel: "Интерфейс:",
    pasteBtnTitle: "Вставить",
    serviceLabel: "Сервис:",
    sourceLangLabel: "Язык исходного текста",
    sourcePlaceholder: "Введите текст...",
    targetLang1Label: "Язык перевода 1",
    targetLang2Label: "Язык перевода 2",
    translateButtonText: "Перевести",
    translation1Placeholder: "Перевод 1",
    translation2Placeholder: "Перевод 2",
  },
  tr: {
    autoTranslateLabel: "Otomatik çeviri",
    copyBtnTitle: "Kopyala",
    interfaceLabel: "Arayüz:",
    pasteBtnTitle: "Yapıştır",
    serviceLabel: "Servis:",
    sourceLangLabel: "Kaynak Dil",
    sourcePlaceholder: "Metin girin...",
    targetLang1Label: "Hedef Dil 1",
    targetLang2Label: "Hedef Dil 2",
    translateButtonText: "Çevir",
    translation1Placeholder: "Çeviri 1",
    translation2Placeholder: "Çeviri 2",
  },
  uk: {
    autoTranslateLabel: "Автопереклад",
    copyBtnTitle: "Копіювати",
    interfaceLabel: "Інтерфейс:",
    pasteBtnTitle: "Вставити",
    serviceLabel: "Сервіс:",
    sourceLangLabel: "Мова оригіналу",
    sourcePlaceholder: "Введіть текст...",
    targetLang1Label: "Мова перекладу 1",
    targetLang2Label: "Мова перекладу 2",
    translateButtonText: "Перекласти",
    translation1Placeholder: "Переклад 1",
    translation2Placeholder: "Переклад 2",
  },
};

const languageNames = {
  en: {
    en: "English",
    uk: "Ukrainian",
    ru: "Russian",
    de: "German",
    nl: "Dutch",
    pl: "Polish",
    pt: "Portuguese",
    fr: "French",
    tr: "Turkish",
  },
  ru: {
    en: "Английский",
    uk: "Украинский",
    ru: "Русский",
    de: "Немецкий",
    nl: "Голландский",
    pl: "Польский",
    pt: "Португальский",
    fr: "Французский",
    tr: "Турецкий",
  },
  uk: {
    en: "Англійська",
    uk: "Українська",
    ru: "Російська",
    de: "Німецька",
    nl: "Голландська",
    pl: "Польська",
    pt: "Португальська",
    fr: "Французька",
    tr: "Турецька",
  },
  de: {
    en: "Englisch",
    uk: "Ukrainisch",
    ru: "Russisch",
    de: "Deutsch",
    nl: "Niederländisch",
    pl: "Polnisch",
    pt: "Portugiesisch",
    fr: "Französisch",
    tr: "Türkisch",
  },
  nl: {
    en: "Engels",
    uk: "Oekraïens",
    ru: "Russisch",
    de: "Duits",
    nl: "Nederlands",
    pl: "Pools",
    pt: "Portugees",
    fr: "Frans",
    tr: "Turks",
  },
  pl: {
    en: "Angielski",
    uk: "Ukraiński",
    ru: "Rosyjski",
    de: "Niemiecki",
    nl: "Niderlandzki",
    pl: "Polski",
    pt: "Portugalski",
    fr: "Francuski",
    tr: "Turecki",
  },
  pt: {
    en: "Inglês",
    uk: "Ucraniano",
    ru: "Russo",
    de: "Alemão",
    nl: "Holandês",
    pl: "Polonês",
    pt: "Português",
    fr: "Francês",
    tr: "Turco",
  },
  fr: {
    en: "Anglais",
    uk: "Ukrainien",
    ru: "Russe",
    de: "Allemand",
    nl: "Néerlandais",
    pl: "Polonais",
    pt: "Portugais",
    fr: "Français",
    tr: "Turc",
  },
  tr: {
    en: "İngilizce",
    uk: "Ukraynaca",
    ru: "Rusça",
    de: "Almanca",
    nl: "Felemenkçe",
    pl: "Lehçe",
    pt: "Portekizce",
    fr: "Fransızca",
    tr: "Türkçe",
  },
};
